POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0NDg1NzQ2LCJ1c2VySWQiOjF9.2XXiLP1DqLZIk6GcCtJbyyrAEg9RtulVIfglubfTtLo

{
    "name": "Test Event aaa",
    "description": "another tesst event ",
    "location": "new location test event",
    "dateTime": "2024-01-02T15:30:00.000Z"
}