Delete http://localhost:8080/events/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0MzE2NjMyLCJ1c2VySWQiOjJ9.G1XSlWZTFtsHE9Rxnde0DK7PcZx0HtasGsvDsLTsJbI
