PUT http://localhost:8080/events/1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0MzE2NjMyLCJ1c2VySWQiOjJ9.G1XSlWZTFtsHE9Rxnde0DK7PcZx0HtasGsvDsLTsJbI


{
    "name": "Updated test event",
    "description": "Updated test event description",
    "location": "new test location update",
    "dateTime": "2024-05-02T15:30:00Z"
}
