PUT http://localhost:8080/events/4
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0NDg0MzkzLCJ1c2VySWQiOjJ9.rhMZsbTNy40P38JTcQ1pM8Fwwy9xwpTmuMjrgYRgPxY


{
    "name": "Updated test event",
    "description": "Updated test event description",
    "location": "new test location update",
    "dateTime": "2024-05-02T15:30:00Z"
}
