PUT http://localhost:8080/events/1
content-type: application/json

{
    "name": "Updated test event",
    "description": "Updated test event description",
    "location": "new test location update",
    "dateTime": "2024-05-02T15:30:00Z"
}
